REM   Script: Session 01
REM   ttt

create table DEPARTAMENTO( 
    COD_DEPART NUMBER(4) COSTRAINT PK_COD_DEPART PRIMARY KEY, 
    NOME_DEPART VARCHAR(30) NOT NULL, 
    DATA_INICIAL DATE 
);

create table DEPARTAMENTO( 
    COD_DEPART NUMBER(4) CONSTRAINT PK_COD_DEPART PRIMARY KEY, 
    NOME_DEPART VARCHAR(30) NOT NULL, 
    DATA_INICIAL DATE 
);

DROP TABLE DEPARTAMENTO;

create table DEPARTAMENTO( 
    COD_DEPART NUMBER(4) CONSTRAINT PK_COD_DEPART PRIMARY KEY, 
    NOME_DEPART VARCHAR(30) NOT NULL, 
    DATA_INICIAL_DEPART DATE 
);

CREATE TABLE PROJETO( 
    COD_PROJ NUMBER(4) CONSTRAINT PK_COD_PROJ PRIMARY KEY, 
    COD_DEPART NUMBER(4) CONSTRAINT FK_COD_DEPART REFERENCES DEPARTAMENTO(COD_DEPART), 
    TITULO_PROJ VARCHAR(30) NOT NULL, 
    DESCRICAO_PROJ VARCHAR(30), 
    DATA_CAD_PROJ DATE DEFAULT SYSDATE 
);

CREATE TABLE LOCALIZACAO( 
    COD_DEPART NUMBER(4) CONSTRAINT FK_COD_DEPART REFERENCES DEPARTAMENTO(COD_DEPART), 
    LOCAL_LOC VARCHAR(252) 
    CONSTRAINT LOCALIZACAO PRIMARY KEY(COD_DEPART, LOCAL_LOC) 
);

CREATE TABLE LOCALIZACAO( 
    COD_DEPART NUMBER(4) CONSTRAINT FK_COD_DEPART REFERENCES DEPARTAMENTO(COD_DEPART), 
    LOCAL_LOC VARCHAR(252), 
    CONSTRAINT LOCALIZACAO PRIMARY KEY (COD_DEPART, LOCAL_LOC) 
);

CREATE TABLE LOCALIZACAO( 
    COD_DEPART NUMBER(4) CONSTRAINT FK_COD_DEPART REFERENCES DEPARTAMENTO(COD_DEPART), 
    LOCAL_LOC VARCHAR(252), 
    CONSTRAINT ID_LOCALIZACAO PRIMARY KEY (COD_DEPART, LOCAL_LOC) 
);

DROP TABLE LOCALIZACAO;

create table DEPARTAMENTO( 
    COD_DEPART NUMBER(4) CONSTRAINT PK_COD_DEPART PRIMARY KEY, 
    NOME_DEPART VARCHAR(30) NOT NULL, 
    DATA_INICIAL_DEPART DATE 
);

DROP TABLE LOCALIZACAO;

CREATE TABLE PROJETO( 
    COD_PROJ NUMBER(4) CONSTRAINT PK_COD_PROJ PRIMARY KEY, 
    COD_DEPART NUMBER(4) CONSTRAINT FK_COD_DEPART REFERENCES DEPARTAMENTO(COD_DEPART), 
    TITULO_PROJ VARCHAR(30) NOT NULL, 
    DESCRICAO_PROJ VARCHAR(30), 
    DATA_CAD_PROJ DATE DEFAULT SYSDATE 
);

DROP TABLE LOCALIZACAO;

CREATE TABLE LOCALIZACAO( 
    COD_DEPART NUMBER(4) CONSTRAINT FK_COD_DEPART REFERENCES DEPARTAMENTO(COD_DEPART), 
    LOCAL_LOC VARCHAR(252), 
    CONSTRAINT ID_LOCALIZACAO PRIMARY KEY (COD_DEPART, LOCAL_LOC) 
);

CREATE TABLE LOCALIZACAO( 
    COD_DEPART NUMBER(4) CONSTRAINT FK_COD_DEPART REFERENCES DEPARTAMENTO(COD_DEPART), 
    LOCAL_LOC VARCHAR(252), 
    CONSTRAINT ID_LOCALIZACAO PRIMARY KEY (COD_DEPART, LOCAL_LOC) 
);

CREATE TABLE LOCALIZACAO( 
    COD_DEPART NUMBER(4) CONSTRAINT FK_COD_DEPART_LOC REFERENCES DEPARTAMENTO(COD_DEPART), 
    LOCAL_LOC VARCHAR(252), 
    CONSTRAINT LOCALIZACAO PRIMARY KEY (COD_DEPART, LOCAL_LOC) 
);

create table DEPARTAMENTO( 
    COD_DEPART NUMBER(4) CONSTRAINT PK_COD_DEPART PRIMARY KEY, 
    NOME_DEPART VARCHAR(30) NOT NULL, 
    DATA_INICIAL_DEPART DATE 
);

CREATE TABLE PROJETO( 
    COD_PROJ NUMBER(4) CONSTRAINT PK_COD_PROJ PRIMARY KEY, 
    COD_DEPART NUMBER(4) CONSTRAINT FK_COD_DEPART REFERENCES DEPARTAMENTO(COD_DEPART), 
    TITULO_PROJ VARCHAR(30) NOT NULL, 
    DESCRICAO_PROJ VARCHAR(30), 
    DATA_CAD_PROJ DATE DEFAULT SYSDATE 
);

CREATE TABLE LOCALIZACAO( 
    COD_DEPART NUMBER(4) CONSTRAINT FK_COD_DEPART_LOC REFERENCES DEPARTAMENTO(COD_DEPART), 
    LOCAL_LOC VARCHAR(252), 
    CONSTRAINT LOCALIZACAO PRIMARY KEY (COD_DEPART, LOCAL_LOC) 
);

CREATE TABLE FUNCIONARIO( 
    COD_FUNC NUMBER(4) CONSTRAINT PK_COD_FUNC PRIMARY KEY, 
    NOME_FUNC VARCHAR(100), 
    CPF_FUNC VARCHAR(15), 
    SALARIO_FUNC NUMBER(4,2) 
     
);

CREATE TABLE FUNCIONARIO( 
    COD_FUNC NUMBER(4) CONSTRAINT PK_COD_FUNC PRIMARY KEY, 
    NOME_FUNC VARCHAR(100), 
    CPF_FUNC VARCHAR(15), 
    SALARIO_FUNC NUMBER(4,2) 
     
);

CREATE TABLE FUNCIONARIO( 
    COD_FUNC NUMBER(4) CONSTRAINT PK_COD_FUNC PRIMARY KEY, 
    NOME_FUNC VARCHAR(100), 
    CPF_FUNC VARCHAR(15), 
    SALARIO_FUNC NUMBER(4,2) 
     
);

create table DEPARTAMENTO( 
    COD_DEPART NUMBER(4) CONSTRAINT PK_COD_DEPART PRIMARY KEY, 
    NOME_DEPART VARCHAR(30) NOT NULL, 
    DATA_INICIAL_DEPART DATE 
);

CREATE TABLE PROJETO( 
    COD_PROJ NUMBER(4) CONSTRAINT PK_COD_PROJ PRIMARY KEY, 
    COD_DEPART NUMBER(4) CONSTRAINT FK_COD_DEPART REFERENCES DEPARTAMENTO(COD_DEPART), 
    TITULO_PROJ VARCHAR(30) NOT NULL, 
    DESCRICAO_PROJ VARCHAR(30), 
    DATA_CAD_PROJ DATE DEFAULT SYSDATE 
);

CREATE TABLE LOCALIZACAO( 
    COD_DEPART NUMBER(4) CONSTRAINT FK_COD_DEPART_LOC REFERENCES DEPARTAMENTO(COD_DEPART), 
    LOCAL_LOC VARCHAR(252), 
    CONSTRAINT LOCALIZACAO PRIMARY KEY (COD_DEPART, LOCAL_LOC) 
);

CREATE TABLE FUNCIONARIO( 
    COD_FUNC NUMBER(4) CONSTRAINT PK_COD_FUNC PRIMARY KEY, 
    NOME_FUNC VARCHAR(100), 
    CPF_FUNC VARCHAR(15), 
    SALARIO_FUNC NUMBER(4,2) 
     
);

DRP TABLE FUNCIONARIO;


DROP TABLE FUNCIONARIO;

create table DEPARTAMENTO( 
    COD_DEPART NUMBER(4) CONSTRAINT PK_COD_DEPART PRIMARY KEY, 
    NOME_DEPART VARCHAR(30) NOT NULL, 
    DATA_INICIAL_DEPART DATE 
);

CREATE TABLE PROJETO( 
    COD_PROJ NUMBER(4) CONSTRAINT PK_COD_PROJ PRIMARY KEY, 
    COD_DEPART NUMBER(4) CONSTRAINT FK_COD_DEPART REFERENCES DEPARTAMENTO(COD_DEPART), 
    TITULO_PROJ VARCHAR(30) NOT NULL, 
    DESCRICAO_PROJ VARCHAR(30), 
    DATA_CAD_PROJ DATE DEFAULT SYSDATE 
);

CREATE TABLE LOCALIZACAO( 
    COD_DEPART NUMBER(4) CONSTRAINT FK_COD_DEPART_LOC REFERENCES DEPARTAMENTO(COD_DEPART), 
    LOCAL_LOC VARCHAR(252), 
    CONSTRAINT LOCALIZACAO PRIMARY KEY (COD_DEPART, LOCAL_LOC) 
);

CREATE TABLE FUNCIONARIO( 
    COD_FUNC NUMBER(4) CONSTRAINT PK_COD_FUNC PRIMARY KEY, 
    NOME_FUNC VARCHAR(100), 
    CPF_FUNC VARCHAR(15), 
    SALARIO_FUNC NUMBER(4,2) 
     
);

DROP TABLE FUNCIONARIO;

CREATE TABLE FUNCIONARIO( 
    COD_FUNC NUMBER(4) CONSTRAINT PK_COD_FUNC PRIMARY KEY, 
    NOME_FUNC VARCHAR(100), 
    CPF_FUNC VARCHAR(15), 
    SALARIO_FUNC NUMBER(4,2) 
     
);

DROP TABLE FUNCIONARIO;

CREATE TABLE FUNCIONARIO( 
    COD_FUNC NUMBER(4) CONSTRAINT PK_COD_FUNC PRIMARY KEY, 
    NOME_FUNC VARCHAR(100) NOT NULL, 
    CPF_FUNC VARCHAR(15) UNIQUE, 
    SALARIO_FUNC NUMBER(4,2) CONSTRAINT CK_SALARIO_FUNC CHECK(SALARIO_FUNC > 1000), 
    ENDERECO_FUNC VARCHAR(252), 
    SEXO_FUNC CHAR(1) CONSTRAINT CK_SEXO_FUNC CHECK(SEXO_FUNC IN('M','F')), 
    COD_SUPERVISOR_FUNC NUMBER(4) CONSTRAINT FK_COD_SUPERVISOR_FUNC REFERENCES FUNCIONARIO(COD_FUNC), 
    COD_DEPART_FUNC NUMBER(4) CONSTRAINT FK_COD_DEPART_FUNC REFERENCES DEPARTAMENTO(COD_DEPART) 
);

CREATE TABLE DEPENDENTE( 
	COD_FUNC_DEPEN NUMBER(4) CONSTRAINT FK_COD_FUNC_DEPEN REFERENCES FUNCIONARIO(COD_FUNC), 
    SEQ_DEPEN NUMBER(4), 
    NOME_DEPEN VARCHAR(100) NOT NULL, 
    PARENTESCO_DEPEN VARCHAR(30) NOT NULL CONSTRAINT CK_PARENTESCO_DEPEN CHECK(PARENTESCO_DEPEN IN('PAI','MAE','IRMAOS','FILHOS')), 
    DATA_NASC_DEPEN DATE, 
    CONSTRAINT DEPENDENTE PRIMARY KEY (COD_FUNC_DEPEN, SEQ_DEPEN) 
 
);

CREATE TABLE PARTICIPA( 
	COD_FUNC_PART NUMBER(4) CONSTRAINT FK_COD_FUNC_PART REFERENCES FUNCIONARIO(COD_FUNC), 
    COD_PROJ_PART NUMBER(4), CONSTRAINT FK_COD_PROJ_PART REFERENCES PROJETO(COD_PROJ), 
    HORAS_PART VARCHAR(50), 
    CONSTRAINT PARTICIPA PRIMARY KEY (COD_FUNC_PART, COD_PROJ_PART) 
);

CREATE TABLE PARTICIPA( 
	COD_FUNC_PART NUMBER(4) CONSTRAINT FK_COD_FUNC_PART REFERENCES FUNCIONARIO(COD_FUNC), 
    COD_PROJ_PART NUMBER(4), CONSTRAINT FK_COD_PROJ_PART REFERENCES PROJETO(COD_PROJ), 
    HORAS_PART VARCHAR(50), 
    CONSTRAINT PARTICIPA PRIMARY KEY (COD_FUNC_PART, COD_PROJ_PART) 
);

CREATE TABLE PARTICIPA( 
	COD_FUNC_PART NUMBER(4) CONSTRAINT FK_COD_FUNC_PART REFERENCES FUNCIONARIO(COD_FUNC), 
    COD_PROJ_PART NUMBER(4) CONSTRAINT FK_COD_PROJ_PART REFERENCES PROJETO(COD_PROJ), 
    HORAS_PART VARCHAR(50), 
    CONSTRAINT PARTICIPA PRIMARY KEY (COD_FUNC_PART, COD_PROJ_PART) 
);

